<?xml version="1.0" encoding="utf-8"?><Database Name="Futhead" Class="PlayerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=5.189.133.51;Initial Catalog=Futhead;User ID=dbadmin" SettingsObjectName="WebRequest.Properties.Settings" SettingsPropertyName="FutheadConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>